/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace SupplyChain {
      
    export type HistoryEntryStruct = {orderId: string, status: BigNumberish, actor: AddressLike, role: string, timestamp: BigNumberish}

    export type HistoryEntryStructOutput = [orderId: string, status: bigint, actor: string, role: string, timestamp: bigint] & {orderId: string, status: bigint, actor: string, role: string, timestamp: bigint }
  
    }

  export interface SupplyChainInterface extends Interface {
    getFunction(nameOrSignature: "createOrder" | "getAllOrderIds" | "getOrderHistory" | "orderHistory" | "orderIds" | "orders" | "updateStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OrderCreated" | "StatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'createOrder', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllOrderIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrderHistory', values: [string]): string;
encodeFunctionData(functionFragment: 'orderHistory', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'orderIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'orders', values: [string]): string;
encodeFunctionData(functionFragment: 'updateStatus', values: [string, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'createOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllOrderIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orderHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orderIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateStatus', data: BytesLike): Result;
  }

  
    export namespace OrderCreatedEvent {
      export type InputTuple = [orderId: string, product: string, quantity: BigNumberish, retailer: AddressLike];
      export type OutputTuple = [orderId: string, product: string, quantity: bigint, retailer: string];
      export interface OutputObject {orderId: string, product: string, quantity: bigint, retailer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatusUpdatedEvent {
      export type InputTuple = [orderId: string, status: BigNumberish, actor: AddressLike, role: string, timestamp: BigNumberish];
      export type OutputTuple = [orderId: string, status: bigint, actor: string, role: string, timestamp: bigint];
      export interface OutputObject {orderId: string, status: bigint, actor: string, role: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SupplyChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): SupplyChain;
    waitForDeployment(): Promise<this>;

    interface: SupplyChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createOrder: TypedContractMethod<
      [_orderId: string, _product: string, _quantity: BigNumberish, _unitPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllOrderIds: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getOrderHistory: TypedContractMethod<
      [_orderId: string, ],
      [SupplyChain.HistoryEntryStructOutput[]],
      'view'
    >
    

    
    orderHistory: TypedContractMethod<
      [arg0: string, arg1: BigNumberish, ],
      [[string, bigint, string, string, bigint] & {orderId: string, status: bigint, actor: string, role: string, timestamp: bigint }],
      'view'
    >
    

    
    orderIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    orders: TypedContractMethod<
      [arg0: string, ],
      [[string, string, bigint, bigint, bigint, string, string, string, string, bigint, bigint, boolean] & {id: string, product: string, quantity: bigint, unitPrice: bigint, totalPrice: bigint, retailer: string, supplier: string, manufacturer: string, distributor: string, status: bigint, timestamp: bigint, exists: boolean }],
      'view'
    >
    

    
    updateStatus: TypedContractMethod<
      [_orderId: string, _newStatus: BigNumberish, _role: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createOrder'): TypedContractMethod<
      [_orderId: string, _product: string, _quantity: BigNumberish, _unitPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllOrderIds'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOrderHistory'): TypedContractMethod<
      [_orderId: string, ],
      [SupplyChain.HistoryEntryStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'orderHistory'): TypedContractMethod<
      [arg0: string, arg1: BigNumberish, ],
      [[string, bigint, string, string, bigint] & {orderId: string, status: bigint, actor: string, role: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'orderIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, bigint, bigint, bigint, string, string, string, string, bigint, bigint, boolean] & {id: string, product: string, quantity: bigint, unitPrice: bigint, totalPrice: bigint, retailer: string, supplier: string, manufacturer: string, distributor: string, status: bigint, timestamp: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'updateStatus'): TypedContractMethod<
      [_orderId: string, _newStatus: BigNumberish, _role: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OrderCreated'): TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
getEvent(key: 'StatusUpdated'): TypedContractEvent<StatusUpdatedEvent.InputTuple, StatusUpdatedEvent.OutputTuple, StatusUpdatedEvent.OutputObject>;

    filters: {
      
      'OrderCreated(string,string,uint256,address)': TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
      OrderCreated: TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
    

      'StatusUpdated(string,uint8,address,string,uint256)': TypedContractEvent<StatusUpdatedEvent.InputTuple, StatusUpdatedEvent.OutputTuple, StatusUpdatedEvent.OutputObject>;
      StatusUpdated: TypedContractEvent<StatusUpdatedEvent.InputTuple, StatusUpdatedEvent.OutputTuple, StatusUpdatedEvent.OutputObject>;
    
    };
  }